context('Navigation', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3001/')
    cy.contains('DESTINATION').click()
    cy.contains('moon').click()
    cy.contains('mars').click()
    cy.contains('europa').click()
    cy.contains('titan').click()
    cy.contains('CREW').click()
    cy.get('[data-testid="MarkShuttleworth"]').click()
    cy.get('[data-testid="VictorGlover"]').click()
    cy.get('[data-testid="AnoushehAnsari"]').click()
    cy.contains('TECHNOLOGY').click()
    cy.get('[data-testid="spaceport"]').click()
    cy.get('[data-testid="spaceCapsule"]').click()
    cy.contains('HOME').click()
  })

  it('cy.go() - go back or forward in the browser\'s history', () => {
    cy.location('pathname').should('eq', '/')

    cy.go('back')
    cy.location('pathname').should('eq', '/technology/spaceCapsule')
    cy.go('back')
    cy.location('pathname').should('eq', '/technology/spaceport')
    cy.go('back')
    cy.location('pathname').should('eq', '/technology/launchVehicle')

    cy.go('back')
    cy.location('pathname').should('eq', '/crew/AnoushehAnsari')
    cy.go('back')
    cy.location('pathname').should('eq', '/crew/VictorGlover')
    cy.go('back')
    cy.location('pathname').should('eq', '/crew/MarkShuttleworth')
    cy.go('back')
    cy.location('pathname').should('eq', '/crew/DouglasHurley')

    cy.go('back')
    cy.location('pathname').should('eq', '/destination/titan')
    cy.go('back')
    cy.location('pathname').should('eq', '/destination/europa')
    cy.go('back')
    cy.location('pathname').should('eq', '/destination/mars')
    cy.go('back')
    cy.location('pathname').should('eq', '/destination/moon')

    cy.go('back')
    cy.location('pathname').should('eq', '/')

    cy.go('forward')
    cy.location('pathname').should('eq', '/destination/moon')
    cy.go('forward')
    cy.location('pathname').should('eq', '/destination/mars')
    cy.go('forward')
    cy.location('pathname').should('eq', '/destination/europa')
    cy.go('forward')
    cy.location('pathname').should('eq', '/destination/titan')

    cy.go('forward')
    cy.location('pathname').should('eq', '/crew/DouglasHurley')
    cy.go('forward')
    cy.location('pathname').should('eq', '/crew/MarkShuttleworth')
    cy.go('forward')
    cy.location('pathname').should('eq', '/crew/VictorGlover')
    cy.go('forward')
    cy.location('pathname').should('eq', '/crew/AnoushehAnsari')

    cy.go('forward')
    cy.location('pathname').should('eq', '/technology/launchVehicle')
    cy.go('forward')
    cy.location('pathname').should('eq', '/technology/spaceport')
    cy.go('forward')
    cy.location('pathname').should('eq', '/technology/spaceCapsule')

    cy.go('forward')
    cy.location('pathname').should('eq', '/')
  })
})